### ISSUE TITLE
Add ability to specify endpoint

### ISSUE THREAD

**Issue by jjjordanmsft** [Microsoft/ApplicationInsights-Docker#24]
I need the ability to specify the endpoint the SDK will use to send telemetry.  This is doable through the Java SDK [1], but I would need to be able to specify this on the commandline, preferably in the same manner as the current ikey= parameter.

[1] It looks like it's a matter of building your own InProcessTelemetryChannel with the proper endpoint and ikey and handing that to the TelemetryConfiguration.

**Comment by jjjordanmsft** [comment]
Hm, I suppose I could probably write-over the configuration xml to specify it as well.  I might look into doing that.

**Comment by Yonisha** [comment]
Hi Jordan,

Yes, this is possible since we first try to read the configuration file from disk.
Therefore, all you need to do is to **add applicationinsights.xml under folder**: **'/usr/docker/ApplicationInsights-Docker/build/docker/'**, with the following content:

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings" schemaVersion="2014-05-30">
	<Channel type="com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel">
	    <EndpointAddress>a-valid-url</EndpointAddress>
	</Channel>
</ApplicationInsights>
```
