### ISSUE TITLE
Resurrect This Project

### ISSUE THREAD

**Issue by dagrooms52** [Microsoft/ApplicationInsights-Docker#25]
Hey guys,

Can we bring this project back to life? I'm trying to use it on a Raspberry Pi, and the only available Java versions I can use are the ones on dockerhub built for ARM CPU. The latest I've found is 1.8.111 from [Hypriot](https://hub.docker.com/r/hypriot/rpi-java/tags/).

Thanks!

**Comment by olljanat** [comment]
@Yonisha @galhag is there any plans to continue developing this one or is there some other tool which replaces this one?

**Comment by SergeyKanzhelev** [comment]
@xiaomi7732, @karolz-ms can this be replaced by any project you are running like https://github.com/Microsoft/ApplicationInsights-Kubernetes/?

**Comment by dagrooms52** [comment]
If it's any help, I ended up making my own container for this solution:
https://hub.docker.com/r/dagrooms52/app-insights-resource-metrics/

**Comment by olljanat** [comment]
@SergeyKanzhelev that one is used to enhance container monitoring. Not host it selves where this project can be used (and what I'm currently looking for).

@dagrooms52 thanks for info. Unfortunately you are also used Python is bit tricky to get working on Windows containers but I probably will try that anyway unless someone comes back with some better option.

What I'm looking for is get Windows container host events to Application Insights and it feels bit odd that there is no solution provided by Microsoft.

**Comment by xiaomi7732** [comment]
@SergeyKanzhelev [Application Insights Kubernetes](https://github.com/Microsoft/ApplicationInsights-Kubernetes/) is .net core specific. @karolz-ms?

**Comment by olljanat** [comment]
@yantang-msft events/log messages which comes out from dockerd.exe. 

Other side is of course host telemetry which is basic feature on this plugin but can be currently only used with Linux hosts. There is some info on documentation: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-docker#run-the-application-insights-monitor-on-your-host

Point is to have ability to see Docker hosts statuses/get alerts from them from same place where we have application monitoring.

**Comment by SergeyKanzhelev** [comment]
CC: @keikhara as well. Seems like containers insights requirement. 


> For logs I would try fluentd log driver with fluentd ApplicationInsights output plugin.
> For metrcs/stats I would try Telegraf, specifically Telegraf Docker input plugin with ApplicationInsigths 
output

@karolz-ms, it would be great if you can submit PR into this repo and in docs with this information. Perhaps references to step-by-step guides would be useful.

**Comment by karolz-ms** [comment]
@SergeyKanzhelev 

I would prefer that the owners of this project (is it you?) add a doc snippet communicating the long-term plans for the project. As part of this we can redirect people to alternatives.

As to step-by-step guides for alternatives I mentioned above, I am not aware of any existing docs that involve specific combination of inputs & outputs I have mentioned. They could be certainly written up and published ... but at the moment my schedule is pretty full till at least mid-September, with work that both has broad impact and primarily deals with improving Application Insights experience for containerized workloads. That is why that work takes higher priority than this. I am not trying to be difficult here, just attempting to be transparent and explain why  in foreseeable future I cannot take on this task you asked me to do. Hope you understand.

**Comment by olljanat** [comment]
Last commit to this project is done over two years ago and also this issue have been open almost year now so I was quite skeptic that if commenting this one will change anything. So it nice to see that there is lot of good discussion on going :)

Anyway, that Telegraf with Docker input and AI output looks to be near of what I'm looking for.
Only problems are that:
- there is no containerized version for Windows
- there is no documentation ready for this combination.

Probably best idea would be write down here that this project is deprecated and open issue to Telegraf project to discuss how to implement these missing things.

I can help to implement these but I would like to see that you together with Telegraf will make sure that this combination will then keep working on future too.

**Comment by karolz-ms** [comment]
@olljanat Telegraf has dozens of inputs and outputs, so it is unrealistic to expect that someone will document a particular combination. That said, the Application Insights output confirms to the contract for Telegraf outputs, has been extensively reviewed by Telegraf lead developers and has [a good set of tests](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/application_insights/application_insights_test.go). It is designed to work with any metric data coming from Telegraf pipeline, regardless which input produced the data. That is why it is included in the basic Telegraf Docker image. If there is a problem with this output, open a GitHub issue and myself or someone from my team will take a look and fix it.

Regarding Windows-based Telegraf images, this is something you need to bring up with Telegraf maintainers--I have no information what their plans are with respect to this.

**Comment by olljanat** [comment]
@karolz-ms sorry if wrote unclearly. I didn't mean necessarily you or your team but more likely this project maintainers / whoever have wrote current documentation: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-docker#run-the-application-insights-monitor-on-your-host

IMO, that should be updated and I think that many would see it useful to have example documentation how to get metrics from Windows containers to Application Insights as they both are Microsoft products it is hard to believe if anyone from Microsoft is not interested about that.

**Comment by karolz-ms** [comment]
@olljanat Completely agree and sorry I misunderstood your earlier post

**Comment by karolz-ms** [comment]
@olljanat I am going to try to find the owner of the Docker tile and see if it can be cajoled to work with custom metrics.

However, a simpler solution might be to just build your own visualization. Application Insights can build graphs on top of any metric and the end effect will be very similar to the Docker tile, see https://docs.microsoft.com/en-us/azure/application-insights/app-insights-metrics-explorer

**Comment by olljanat** [comment]
@karolz-ms ok thanks. It would be simplest to have ready made Tile which we can use on all envs.

**Comment by karolz-ms** [comment]
@olljanat so I am being told that [Container Insights](https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-containers) is the recommended solution for container monitoring, one that is getting most investment, and that Container Insights and Application Insights teams are actively working on blending the two experiences together. Once this arrives, your requirement for "ready made tile" (and more) should be fulfilled.

In the meantime your own visualization with Metrics Explorer is probably best bet, putting you in control of your destiny, because the old Docker tile is heading for retirement.
